### ISSUE TITLE
All Empty!! In client Area!

### ISSUE THREAD

**Issue by sonuyos** [GiovanniMounir/onlinenet-module#1]
Hi I am facing this error - http://prntscr.com/5kg02t

Btw LOVELY Script <3!!

 Loving it! But kinda unuseable!!

**Comment by GiovanniMounir** [comment]
Hi Sonuyos,

It looks like you haven't copied the files in the correct place, please make sure you have copied the files to /modules/servers/**online** then try again! Also, make sure you have inserted the correct variables into the server properties. This includes your online.net's private token (into the server access hash field) and the online.net server ID (into the server username field)

**Comment by sonuyos** [comment]
Hi Verelox,

I have fixed out the problem, actually I was entering the Private Access token in Password slot, dumb me :P

However, you may wanna consider fixing locationg of files...

like everything is set as "/clientarea.php" & "/modules/"

please remove "/" from the script as it is redirecting to domain.com/clientarea.php instead of domain.com/whmcs/clientarea.php

**Comment by GiovanniMounir** [comment]
I'm glad it worked, and thank you very much for the suggestion! I have applied the changes, please try again with the new files, but make sure you remove the cache files from /templates_c first.

**Comment by OpenIaaS** [comment]
I do not think issue with urls is fixed I download zip it this morning and it's poiniting to  domain.com/clientarea.php not to  domain.com/mybillingfolder/clientarea.php

Any way its easy fix 

Thanks for the module

**Comment by sonuyos** [comment]
@DanielCik not really, you need to do it manually!! That's how i did :)

**Comment by OpenIaaS** [comment]
yes i fixed it :) /clientarea.php => clientarea.php easy gedit replace all but I get impression that it is all ready fixed

**Comment by GiovanniMounir** [comment]
Spot on! I have applied the changes, thanks guys!
