### ISSUE TITLE
Domain name

### ISSUE THREAD

**Issue by FredericGalline** [GiovanniMounir/onlinenet-module#2]
Hi,

Just one question, is your module work with online.net domain ? is it possible to buy a domain via whmcs ?

thanks a lot,
Fred

**Comment by GiovanniMounir** [comment]
Hi Fred, this module is only for online.net resellers as it gives the WHMCS client the permission to manage a specific server from your online.net account through the API; but it's not for reselling online.net domains, if that's what you meant.
