### ISSUE TITLE
Not compatible with 6.0

### ISSUE THREAD

**Issue by sonuyos** [GiovanniMounir/onlinenet-module#4]
Can we update the script together?

Would love if it gets supported for 6.0 as well :)

**Comment by GiovanniMounir** [comment]
Hi sonuyos! I would have loved to update this with you, but I unfortunately cannot as I no longer have a valid/licensed copy of WHMCS - you may feel free to modify the files, make a pull request and I'll be happy to merge your changes under a new release.

My apologizes for the slow response!

**Comment by sonuyos** [comment]
Ahh no problem,
though u can join me as well, that way we can both do it as its ur script and i have not much knowledge about it :)

**Comment by GiovanniMounir** [comment]
That would be awesome! As far as I'm aware, no changes to online.net's API would need to be carried out, so only WHMCS' variables I think. Let me know how I can be of help and I'll happily assist!

**Comment by sonuyos** [comment]
i tried some things, but still cannot understand it fully, as this is new to me and i know php mostly, little i understand about this 6.0...

**Comment by betaboy44** [comment]
#Sonuyos when you are successful in upgrading this module for whmcs v6 then please share with me also :)

**Comment by sonuyos** [comment]
I have already done that.

**Comment by betaboy44** [comment]
@sonuyos what have you done O.o

**Comment by sonuyos** [comment]
Sorry didnt read properly, Am still working over it, havnt got much time.

**Comment by sonuyos** [comment]
ahh i give up, its out of my knowledge...

@GiovanniMounir i can help you with whmcs, can u help me setting this up?

**Comment by sonuyos** [comment]
Ok updated...

i am able to get it work, but not 100% - http://prntscr.com/82j5lr

Its all empty...still exploring though :)

**Comment by sonuyos** [comment]
Ok Done, got it working @betaboy44 just go to general settings and then in security tab and enable smarty php tags..

only 2 issue - 

1st - http://prntscr.com/82jeg9
double double coming

2nd - the raid & network box css is screwed up - http://prntscr.com/82jes8

Am working on it and will try to fix and update the script..

also will try to add reinstall option :)

**Comment by betaboy44** [comment]
@sonuyos 
Nice work,.reinstall option will be nice enough,..
Must share script with me also after fixing it all so that i can make more beautiful theme for it and try to add more features too and provide you back ;)
Presently i not have whmcs v6 for testing or editing so that's why i can't touch it :)

**Comment by GiovanniMounir** [comment]
Awesome progress! Regarding the state getting outputted twice, if you made changes to the PHP/TPL code, I would check the $state variable to ensure no duplicate info is appended; this doesn't happen with the current code on WHMCS v5, I believe.

**Comment by sonuyos** [comment]
no its single...by the by @GiovanniMounir  can you do anything for reinstall option?

**Comment by GiovanniMounir** [comment]
@sonuyos I'm afraid not since it's not documented in their [API](https://console.online.net/en/api/); a workaround would be to connect to their console website then reinstall the server, but this would require the account username and password which is not really a safe way to do it.

**Comment by OpenIaaS** [comment]
Any shared code for WHMCS 6 ? Or can @sonuyos give advice what he change

**Comment by sonuyos** [comment]
@OpenIaaS nope, it wont work as its not on API as @GiovanniMounir said...

**Comment by OpenIaaS** [comment]
I do not ask reinstall option just for module working for whmcs6 version (I'm not a dev I use git hub to save code from disappearance )

**Comment by sonuyos** [comment]
@OpenIaaS please read my previous comment i have mentioned how to do it :)

**Comment by Cavain** [comment]
@sonuyos I need your all settings fixed file please send me that file here > lashmovie@gmail.com

**Comment by sonuyos** [comment]
@Cavain you should definitely work on your manners and people's skill.

Also why do you need my "settings"?

**Comment by Cavain** [comment]
@sonuyos i need New CSS and more configure options because, We're providing more better service to our customers that's why am trying to configure that module more better but its hard.

**Comment by Cavain** [comment]
@sonuyos i see WHMCS Modules list and i found Online.net module its looking awsome and i want that , if i bought that one time then we configure our Open source module? means that if we change the css and other commands?

**Comment by xpleet** [comment]
Hi @sonuyos, did you fix the double output in stat ?
I tried to check the code and looks like $state isn't appended. Any idea how to fix it ?
Thanks !
