### ISSUE TITLE
Security Fix + Latest Upgrade

### ISSUE THREAD

**Issue by eclipsed-ninja** [GiovanniMounir/onlinenet-module#7]
Just used your module and brought about security changes and support for WHMCS v6.X

and was wondering if you might allow me to either upload the code under my account and you place a redirect or add me as a contributor to your project so I can push the updates and maintain it.

If you got anymore questions, Feel free to ping me on twitter.

**Comment by GiovanniMounir** [comment]
Sure, it would be greatly appreciated if you could help! Thank you very much.

**Comment by GiovanniMounir** [comment]
I tried to reach you over Twitter but it appears that you weren't available. You may feel free to upload the code and I'll be happy to add your updates, or you can reach me via Twitter.
