### ISSUE TITLE
No happen !

### ISSUE THREAD

**Issue by ghost** [GiovanniMounir/onlinenet-module#8]
Hello,

I uploaded this module in whmcs v6 .
I added a server and I see module command ( Suspend , Unsuspend , Reboot , Terminate )

I try to reboot server via WHMCS. it shows "Action Completed Successfully" but No happen !!
Also there isn't Management of the server state .

**Comment by GiovanniMounir** [comment]
Hello,

The module might not be compatible with WHMCS v6, please refer to @sonuyos comments at https://github.com/Verelox/onlinenet-module/issues/4 for workarounds.
