### ISSUE TITLE
Module Integration Issue

### ISSUE THREAD

**Issue by Cavain** [GiovanniMounir/onlinenet-module#9]
Hi,

I'm trying to integrate that module in my WHMCS V6.3 , after uploading and extracting in modules/servers/online . Then i add new server , Server ID , and Private API key added in Hash Access then i check that module in my test client area and there is not showing any of server options .
## Best Regards,

Johnny

**Comment by GiovanniMounir** [comment]
Hello,

The module was last tested on WHMCS v5, so I believe it might not be compatible. @sonuyos once got it working by enabling "Smarty PHP tags" from the General Settings tab as explained [here](https://github.com/Verelox/onlinenet-module/issues/4) - does enabling this option fix the issue?
